# Generated by Django 6.0.4 on 2026-04-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.IntegerField(blank=True, help_text='AI Match Percentage (0-100)', null=True),
        ),
    ]
